---
output:
  html_document:
    toc: false
    theme: spacelab
  knitrBootstrap::bootstrap_document:
    theme.chooser: TRUE
    highlight.chooser: TRUE
---

protocols
=========

Here you can find a set of lab analysis protocols.


### RNA-sequencing

* [Analyzing RNA-seq data with the "Tuxedo" tools](tophat_cufflinks/)
* [eQTL analysis with Ballgown](ballgown_eqtl/)
* [Creating a count matrix from BigWig files](bigwig_DEanalysis/)

### Package development

* [Routinely testing your R package with Travis](travis_bioc_devel/)
* [Leek group guide to R packages](https://github.com/jtleek/rpackages)


### Analyzing data

* [Repositories at `leekgroup`](leekgroup_repo/)

### Submitting protocols

* [How to submit a new protocol](submit_protocol/)



If you are a member at Leek group and want to contribute a template, please check [how to submit a new protocol](submit_protocol/). Basically, fork the repository, copy [protocol template](protocol_template/) to a new directory, modify it to your liking, update this page, and submit a pull request.


Date this page was last modified: `r Sys.time()`.
